### ISSUE TITLE
Use of Alberto's pretrained model with Huggingface's Transformer package

### ISSUE THREAD

**Issue by aesuli** [marcopoli/AlBERTo-it#1]
I would like to use Alberto's pretrained model with [Huggingface's Transformer](https://github.com/huggingface/transformers) package.
Can you provide the model in a format that's compatible/loadable with that package?

**Comment by marcopoli** [comment]
The model has been uploaded on huggingface.co and now it is usable as described into the readme

```python
from tokenizer import *
from transformers import AutoTokenizer, AutoModel

a = AlBERTo_Preprocessing(do_lower_case=True)
s: str = "#IlGOverno presenta le linee guida sulla scuola #labuonascuola - http://t.co/SYS1T9QmQN"
b = a.preprocess(s)

tok = AutoTokenizer.from_pretrained("m-polignano-uniba/bert_uncased_L-12_H-768_A-12_italian_alb3rt0")
tokens = tok.tokenize(b)
print(tokens)

model = AutoModel.from_pretrained("m-polignano-uniba/bert_uncased_L-12_H-768_A-12_italian_alb3rt0")
```

**Comment by aesuli** [comment]
Great! Thank you so much Marco.

**Comment by marcodeleonardis** [comment]
Hi. I have succesfully downloaded the model and executed the code to load tokenizer and model as explained. How can I use it to perfor a sentiment on a single sentence? I would like to obtain something like:

s: str = "#IlGOverno presenta le linee guida sulla scuola #labuonascuola - http://t.co/SYS1T9QmQN"
model.predict(s) -> [0.89659865, 0.112343424]
